force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Season__c/fields/TV_Serie__c.field-meta.xml
<CustomField>
    <fullName>TV_Serie__c</fullName>
    <label>TV Serie</label>
    <referenceTo>TV_Serie__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Serie__c/TV_Serie__c.object-meta.xml
<CustomObject>
    <label>TV Serie</label>
    <nameField>
        <label>TV Serie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SeasonHandler.cls
public with sharing class SeasonHandler {
       public static void checkUniqueSeasonFieldsByTVSerieId (List<Season__c> seasons) {
        if(seasons == null){
            return;
        }

        for(Season__c season : seasons){
            List<Season__c> tvSerieSeasons = [SELECT Name, Order__c FROM Season__c
                WHERE TV_Serie__c = :season.TV_Serie__c AND Id <> :season.Id];
            
            if(tvSerieSeasons.size() > 0){
                for (Season__c tvSerieSeason : tvSerieSeasons) {
                    if(season.Name == tvSerieSeason.Name) {
                    season.AddError('This season name already exist for chosen TV Series.'); 
                    }   
                    if(season.Order__c == tvSerieSeason.Order__c){
                        season.AddError('This order already exist for chosen TV Series.');
                    }
                }
            }                         
        }
    }
}