force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/TV_Serie__c.field-meta.xml
<CustomField>
    <fullName>TV_Serie__c</fullName>
    <label>TV Serie</label>
    <referenceTo>TV_Serie__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TV_Serie__c/TV_Serie__c.object-meta.xml
<CustomObject>
    <label>TV Serie</label>
    <nameField>
        <label>TV Serie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SeasonController.cls
/**
 * @author Adrianna Zajac <adrianna.zajac@accenture.com>
 * @date 29/03/2024
 * @description This class provides method that gets Seasons data.
 */
public with sharing class SeasonController {
    /**
     * @author Adrianna Zajac <adrianna.zajac@accenture.com>
     * @date 29/03/2024
     * @description The method returns list of all Seasons of chosen TV Serie.
     * 
     * @param tvSerieId Id of the chosen TV Serie.
     */
    @AuraEnabled(cacheable=true)
    public static Season__c[] getAllSeasonsByTvSerieId(Id tvSerieId){
        try {
            return [
                SELECT Name
                FROM Season__c
                WHERE TV_Serie__c = :tvSerieId
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}