force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>244</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EpisodeHandler.cls
/**
 * @author Adrianna Zajac <adrianna.zajac@accenture.com>
 * @date 07/04/2024
 * @description This class provides methods for handling Episodes.
 */
public with sharing class EpisodeHandler {
    /**
     * @author Adrianna Zajac <adrianna.zajac@accenture.com>
     * @date 07/04/2024
     * @description The method handles logic before insertion or update of Episode__c records.
     * 
     * @param episodes List of new Episode__c records or Episode__c records with updated data.
     * @param seasonEpisodes List with data existing Episode__c records for particular Season__c.
     */
    public static void checkUniqueEpisodeFieldsBySeasonId (List<Episode__c> episodes) {
        if(episodes == null){
            return;
        }

        for(Episode__c episode : episodes){
            if(episode.Source__c != 'DataImport') {
                List<Episode__c> seasonEpisodes = [SELECT Name, Order__c FROM Episode__c
                WHERE Season__c = :episode.Season__c AND Id <> :episode.Id];
        
                if(seasonEpisodes.size() > 0) {
                    for (Episode__c seasonEpisode : seasonEpisodes) {
                        if(episode.Name == seasonEpisode.Name) {
                            episode.AddError('This episode name already exist for chosen Season.'); 
                        }   
                        if(episode.Order__c == seasonEpisode.Order__c){
                            episode.AddError('This order already exist for chosen Season.');
                        }
                    }
                }   
            }                    
        }
    }
}