force-app/main/default/objects/Episode__c/Episode__c.object-meta.xml
<CustomObject>
    <label>Episode</label>
    <nameField>
        <label>Episode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Episode__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Episode__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Season__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EpisodeController.cls
/**
 * @author Adrianna Zajac <adrianna.zajac@accenture.com>
 * @date 29/03/2024
 * @description This class provides method that gets Episodes data.
 */
public with sharing class EpisodeController {
    /**
     * @author Adrianna Zajac <adrianna.zajac@accenture.com>
     * @date 29/03/2024
     * @description The method returns list of all Episodes of chosen Season and actual page.
     * 
     * @param seasonId Id of the chosen Season.
     * @param page Number of actual page.
     */
    @AuraEnabled(cacheable=false)
    public static EpisodesResponseDTO getAllEpisodesBySeasonId(Id seasonId, Integer page) {
        if(page == null) {
            page = 1;
        }
        EpisodesResponseDTO response = new EpisodesResponseDTO();
        decimal pageSize1 = 10;
        Integer pageSize = 10;
        Integer offset = (page - 1) * pageSize;
        
        try {
            Integer all = [   
                SELECT COUNT()
                FROM Episode__c
                WHERE Season__c = :seasonId
            ];


            response.episodes = [
                SELECT Name, Summary__c
                FROM Episode__c
                WHERE Season__c = :seasonId
                ORDER BY Order__c
                LIMIT :pageSize OFFSET :offset
            ];

            response.page = page;
            response.allFound = all;
            response.allPages = (all / pageSize1).round(System.RoundingMode.UP).intValue();

            System.debug(response);

            return response;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}